version: '3.1'

# To build the image:
# $ docker-compose build
#
# To start all services (postgresql, apache2):
# $ docker-compose run --rm app-nominatim up -d

services:
  app-nominatim:
    build: .
    image: pesho-k/nominatim-docker
    ports:
      - 8181:8080
    restart: always
